- name: create acme.json
  file:
    path: /home/{{ ansible_user }}/acme.json
    state: touch
    mode: "0600"
  tags: traefik

- name: copy traefik.yaml
  copy:
    src: traefik.yaml
    dest: /home/{{ ansible_user }}/traefik_conf.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - traefik

- name: create traefik docker network
  docker_network:
    name: traefik
    state: present
  tags:
    - traefik

- name: create traefik container
  docker_container:
    name: traefik
    image: traefik:v2.10
    restart_policy: unless-stopped
    command:
      [
        "--global.sendAnonymousUsage=false",
        "--entryPoints.web.address=:80",
        "--entrypoints.web.http.redirections.entryPoint.to=websecure",
        "--entrypoints.web.http.redirections.entryPoint.scheme=https",
        "--entrypoints.web.http.redirections.entrypoint.permanent=true",
        "--entrypoints.websecure.address=:443",
        "--api.insecure=true",
        "--providers.docker=true",
        "--providers.docker.endpoint=unix:///var/run/docker.sock",
        "--providers.file.filename=/traefik_conf.yaml",
        "--providers.file.watch=true",
        "--certificatesresolvers.direct-resolver.acme.email={{ traefik_email }}",
        "--certificatesresolvers.direct-resolver.acme.storage=acme.json",
        "--certificatesresolvers.direct-resolver.acme.httpchallenge=true",
        "--certificatesresolvers.direct-resolver.acme.httpchallenge.entrypoint=web",
        "--providers.docker.exposedByDefault=false",
        "--entryPoints.web.forwardedHeaders.insecure",
        "--log.filePath=/var/log/traefik.log",
        "--providers.docker.network=traefik",
      ]
    networks:
      - name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/{{ ansible_user }}/acme.json:/acme.json
      - /home/{{ ansible_user }}/traefik_conf.yaml:/traefik_conf.yaml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  tags:
    - traefik
