# Deploy backend
name: build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Docker Builder 
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}